# Generated by Django 5.2.8 on 2025-11-15 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('chocolate', 'Chocolate'), ('candy', 'Candy'), ('bakery', 'Bakery'), ('gum', 'Gum'), ('other', 'Other')], default='other', max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('purchase', 'Purchase'), ('restock', 'Restock')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_events', to=settings.AUTH_USER_MODEL)),
                ('sweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_events', to='sweets.sweet')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
